version: '3.8'

services:

  forkme-server-blue:
    build:
      context: ./server-docker
      dockerfile: Dockerfile
    container_name: fork-me-blue
    ports:
      - "8083:8080"
    env_file:
      - .env
    volumes:
      - ./app.jar:/app.jar
    networks:
      - app-net

networks:
  app-net:
    external: true
